# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
#  pod 'AgoraAudio_Special_iOS', '4.1.1.7'
  pod 'AgoraRtcEngine_iOS', :path => "/Volumes/T5/PodSpec/Audio50ms/AgoraRtcEngine_iOS.podspec"
  pod "AgoraLyricsScore", :path => "../AgoraLyricsScore.podspec", :testspecs => ['Tests']
  pod "ScoreEffectUI", :path => "../../ScoringEffectUI/ScoreEffectUI/ScoreEffectUI.podspec", :testspecs => ['Tests']
  pod 'RTMTokenBuilder', "1.0.0"
  pod "Zip"
end
